create table process_instance (
    id             uuid         primary key,
    definition_key varchar(100) not null,
    current_step   varchar(100) not null,
    status         varchar(20)  not null,
    context_json   text         not null,
    created_at     timestamptz  not null,
    updated_at     timestamptz  not null,
    version        bigint       not null default 0
);

create index idx_process_instance_status on process_instance (status);
create index idx_process_instance_definition on process_instance (definition_key);

create table process_step_log (
    id          bigint generated by default as identity primary key,
    instance_id uuid         not null references process_instance (id),
    sequence_no integer      not null,
    step        varchar(100) not null,
    outcome     varchar(100),
    disposition varchar(20)  not null,
    started_at  timestamptz  not null,
    finished_at timestamptz  not null,
    error       text,
    constraint uq_process_step_log_instance_seq unique (instance_id, sequence_no)
);

create index idx_process_step_log_instance on process_step_log (instance_id);
